version: "3.9"

services:
  frontend:
    build:
      context: ./fronted-project
    image: dt1_frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

  api:
    build:
      context: ./api-project
    image: dt1_api:latest
    ports:
      - "5050:5050"

